baseURL = "http://localhost:1313/"
languageCode = "id"
title = "Aparencanamu"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
          hardWraps = true #lineBreak
          unsafe = true #htmlMarkdown
          xhtml = false #untukXhtml

[outputs]
home = ["HTML", "RSS"]
page = ["HTML"]

[permalinks]
pages = "/:title/"